name: AndroidDebug
run-name: Compile and Upload Debug APK

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew buildDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.3
        with:
          name: canipark-debug
          path: composeApp/build/outputs/apk/debug/app-debug.apk

      - name: Delete build directory
        run: rm -rf composeApp/build

env:
  API_KEY: ${{ secrets.API_KEY }}
