name: AndroidDeploy
run-name: Deploy AAB to Play Store

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4.1.0

        - name: Set up JDK 17
          uses: actions/setup-java@v4.1.0
          with:
            java-version: '17'
            distribution: 'adopt'

        - name: Grant execute permission for gradlew
          run: chmod +x gradlew

        - name: decrypt service account json
          run: echo ${{ secrets.GOOGLE_SERVICES_JSON  }} | base64 --decode > ./composeApp/src/google-services.json

        - name: decrypt keystore
          run: echo ${{ secrets.SIGNING_KEY_BASE64 }} | base64 --decode > release-keystore.jks

        - name: Build with Gradle
          run: ./gradlew bundleRelease
          env:
            RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
            RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
            RELEASE_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
            RELEASE_STORE_FILE: ../release-keystore.jks

        - name: Sign AAB
          uses: r0adkll/sign-android-release@v1
          with:
              releaseDirectory: composeApp/build/outputs/bundle/release
              signingKeyBase64: ${{ secrets.SIGNING_KEY_BASE64 }}
              alias: ${{ secrets.KEY_ALIAS }}
              keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
              keyPassword: ${{ secrets.KEY_PASSWORD }}

        - name: print signed release directory
          run: ls -l composeApp/build/outputs/bundle/release

        - name: Deploy to Play Console
          uses: r0adkll/upload-google-play@v1.1.3
          with:
              serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
              packageName: com.dugue.canipark
              releaseFiles: composeApp/build/outputs/bundle/release/composeApp-release.aab
              track: internal
              status: draft
              releaseName: ${{ github.run_number }}

        - name: Clean up
          run: rm -rf composeApp/build && rm -rf release-keystore.jks

env:
  API_KEY: ${{ secrets.API_KEY }}