name: AndroidDebug
run-name: Compile and Upload Debug APK

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v4.1.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: decrypt service account json
        run: echo ${{ secrets.GOOGLE_SERVICES_JSON  }} | base64 --decode > ./composeApp/src/google-services.json

      - name: Build with Gradle
        run: ./gradlew buildDebug

      - name: Delete build directory
        run: rm -rf composeApp/build

env:
  API_KEY: ${{ secrets.API_KEY }}
